# Generated by Django 2.2.1 on 2019-08-10 17:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20190810_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
